baseURL = 'https://sparkknow.com/'
languageCode = 'zh-cn'
title = 'sparkknow blog'
theme = "hyde"

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/spark8899/"}
  ]

[params]
  description = "person blog"
